### PR TITLE
add feature too enable users get cities by district

### PR DESCRIPTION
**Pull request by ayinke93**

### CODE REVIEW

**Review by vintagefuture — CHANGES_REQUESTED** [review]
Looks good! Can you also add the call to the method in App.java?

**Comment by salismt** [comment]
looks good from me, yes please add the call to the method in App.java

**Comment by salismt** [comment]
also can you change the base branch to develop instead, this Merge Request is to Master directly

**Comment by ayinke93** [comment]
added then method call and changed the base branch

**Comment by vintagefuture** [comment]
Awesome, looks good! I just spotted a couple of minor things but it's mainly from my previous code, I'll soon push a patch

**Pull request merged**
